name: Scheduled matcher

on:
  schedule:
  - cron: "0 23 * * TUE" # 9am Wednesday Melbourne/Australia

jobs:
  build:
    name: Request matcher command
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d "secret=${{ secrets.MATCH_SECRET }}" https://slack-cafe.vercel.app/command/match
